# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

permissions:
  contents: write
  
on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - .github/workflows/*
      - "**/README.md"

jobs:
  build:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.version.outputs.prop }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with:
        path: Flow.Launcher.Plugin.FlowGet/plugin.json
        prop_path: Version
    - name: Print version
      run: echo ${{ steps.version.outputs.prop }}
    - name: Restore dependencies
      run: dotnet restore FlowGet.slnx
    - name: Build
      run: dotnet publish FlowGet.slnx --no-restore -c Release
    - name: Test
      run: dotnet test FlowGet.slnx --no-build --verbosity normal
    - name: Zip
      working-directory: Flow.Launcher.Plugin.FlowGet/bin/Release/publish
      run: 7z a -tzip ../Flow.Launcher.Plugin.FlowGet.zip *
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FlowLauncherPlugin
        path: Flow.Launcher.Plugin.FlowGet/bin/Release/Flow.Launcher.Plugin.FlowGet.zip


  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: FlowLauncherPlugin
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: Flow.Launcher.Plugin.FlowGet.zip
          tag_name: ${{ needs.build.outputs.version }}